import { test, expect } from '@playwright/test'
const day = (offset = 0) => {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  return d.toISOString().slice(0, 10)
}
test('renewal follow up, daily work, call note, commission and private global search', async ({
  page,
}, info) => {
  page.on('requestfailed', (request) => {
    const url = new URL(request.url())
    if (url.hostname.endsWith('supabase.co'))
      console.log('Network check:', url.pathname, request.failure()?.errorText)
  })
  await page.goto('/login')
  if (process.env.E2E_LIVE === 'true') {
    await page.getByLabel('כתובת אימייל', { exact: true }).fill(process.env.E2E_EMAIL!)
    await page.getByLabel('סיסמה', { exact: true }).fill(process.env.E2E_PASSWORD!)
    await page.getByRole('button', { name: 'כניסה למערכת', exact: true }).click()
  } else await page.getByRole('button', { name: 'כניסה לסביבת הדגמה', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'התמונה המלאה של הסוכנות' })).toBeVisible()
  await page.goto('/customers')
  await page.getByRole('button', { name: 'לקוח חדש', exact: true }).click()
  await page.getByLabel('שם פרטי *', { exact: true }).fill('שיפור')
  await page.getByLabel('שם משפחה', { exact: true }).fill('בדיוני')
  await page.getByLabel('טלפון', { exact: true }).fill('050-000-1234')
  await page.getByRole('dialog').getByRole('button', { name: 'שמירה', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const profile = page.url()
  await expect(page.getByRole('link', { name: 'WhatsApp', exact: true })).toHaveAttribute(
    'href',
    'https://wa.me/972500001234',
  )
  await page.getByRole('button', { name: 'סיכום שיחה', exact: true }).click()
  await page.getByLabel('מה סוכם עם הלקוח?').fill('נקבעה שיחת המשך לבדיקה')
  await page.getByRole('button', { name: 'שמירת סיכום', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('tab', { name: 'פעילות', exact: true }).click()
  await expect(page.getByText('נקבעה שיחת המשך לבדיקה', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'פוליסות (0)', exact: true }).click()
  await page.getByRole('button', { name: 'פוליסה חדשה', exact: true }).click()
  await page.getByLabel('חברת ביטוח *', { exact: true }).fill('חברת שיפור')
  await page.getByLabel('מספר פוליסה', { exact: true }).fill('ENHANCEMENT-123')
  await page.getByLabel('תאריך התחלה *', { exact: true }).fill(day(-5))
  await page.getByLabel('תאריך סיום *', { exact: true }).fill(day(5))
  await page.getByRole('dialog').getByRole('button', { name: 'שמירה', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/renewals')
  await page.getByLabel('חיפוש חידושים').fill('ENHANCEMENT-123')
  await page
    .locator('article')
    .filter({ hasText: 'ENHANCEMENT-123' })
    .getByRole('button', { name: 'עדכון טיפול', exact: true })
    .click()
  await page
    .getByRole('dialog')
    .getByLabel('שלב הטיפול', { exact: true })
    .selectOption('ממתין ללקוח')
  await page.getByLabel('מועד מעקב הבא').fill(day())
  await page.getByLabel('סיכום הטיפול').fill('לחזור היום ללקוח')
  await page.getByRole('button', { name: 'שמירת הטיפול', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/today')
  await expect(page.getByText('חברת שיפור · רכב · ENHANCEMENT-123', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('daily-work.png'), fullPage: true })
  await page.goto('/commissions')
  await page.getByRole('button', { name: 'הצגת כל הפוליסות' }).click()
  const row = page.getByRole('row').filter({ hasText: 'ENHANCEMENT-123' })
  await row.getByRole('button', { name: 'עדכון עמלה' }).click()
  await page.getByLabel('עמלה צפויה בשקלים', { exact: true }).fill('150.25')
  await page.getByLabel('סך העמלה שהתקבלה בשקלים').fill('50')
  await page.getByLabel('תאריך זכאות צפוי').fill(day())
  await page.getByRole('button', { name: 'שמירת עמלה' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row).toContainText('150.25')
  await expect(row).toContainText('100.25')
  await page.goto('/search')
  await page.getByLabel('חיפוש בכל הנתונים', { exact: true }).fill('0500001234')
  await page.getByRole('button', { name: 'חיפוש', exact: true }).click()
  await expect(page.getByRole('button', { name: 'ENHANCEMENT-123', exact: true })).toBeVisible()
  expect(page.url()).not.toContain('0500001234')
  await page.goto('/renewals')
  await page.getByLabel('חיפוש חידושים').fill('ENHANCEMENT-123')
  await page
    .locator('article')
    .filter({ hasText: 'ENHANCEMENT-123' })
    .getByRole('button', { name: 'עדכון טיפול', exact: true })
    .click()
  await page.getByRole('dialog').getByLabel('שלב הטיפול', { exact: true }).selectOption('חודש')
  await page.getByRole('button', { name: 'שמירת הטיפול', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/today')
  await expect(page.getByText('חברת שיפור · רכב · ENHANCEMENT-123', { exact: true })).toHaveCount(0)
  await page.goto(profile)
  await page.getByRole('tab', { name: 'פעילות', exact: true }).click()
  await expect(page.getByText(/חידוש: חודש/)).toBeVisible()
})
